= RPG AsciiDoc template
:author: Chris Barnes

== To do

* [ ] Fix epub
* [ ] Get travis to upload PDF on release
* [ ] Write more about AsciiDoc for RPGs
** [ ] Flesh out ``index.adoc`` with more syntax examples

== Features

Write your RPG rules in plain text, and easily convert it into a web page and PDF (epub soon!).
Manage your edit history with git, and collaborate with others on GitHub.
When you're ready to release it, just tag the git commit and push: the web page will be uploaded to github.io, and other output files will be uploaded to GitHub's releases page.

== Usage

Requires https://git-scm.com/[``git``], a https://github.com[GitHub account], and a https://travis-ci.org[Travis CI] account (you can sign in with GitHub).

. https://help.github.com/en/articles/fork-a-repo[Fork] this repository
. https://travis-ci.org/account/repositories[Enable] your fork's repository on Travis
. https://help.github.com/en/articles/creating-a-personal-access-token-for-the-command-line[Create] an access token on GitHub
. https://docs.travis-ci.com/user/environment-variables/#defining-variables-in-repository-settings[In the Travis settings] for your fork, save this access token as an environment variable, ``GITHUB_TOKEN``

=== Local

Requires modern versions of https://www.ruby-lang.org/en/[ruby] and https://bundler.io/[bundler]

----
# install dependencies
bundle

# build html and pdf to a folder called "out"
rake html
rake pdf

# build all
rake all
# or just
rake
----

=== Releasing online

----
git tag -a v1.0.0 -m "The first version!"
git push --tags
----

== Links

* This template's automatically-generated website
* https://github.com/clbarnes/OpenDoc6/[Example project]
